version: '3.8'

services:
  orderdb:
    image: mcr.microsoft.com/mssql/server
  
  catalogdb:
    image: postgres

  basketdb:
    image: postgres
  
  distributedcache:
    image: redis
  
  messagebroker:
    image: rabbitmq:management

  catalog.api:
    image: catalog.api
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.Api/Dockerfile
  
  basket.api:
    image: basket.api
    build:
      context: .
      dockerfile: Services/Basket/Basket.Api/Dockerfile
  
  discount.grpc:
    image: discount.grpc
    build:
      context: .
      dockerfile: Services/Discount/Discount.Grpc/Dockerfile
  
  ordering.api:
    image: ordering.api
    build:
      context: .
      dockerfile: Services/Ordering/Ordering.Api/Dockerfile
  yarpapigateway:
    image: yarpapigateway
    build:
      context: .
      dockerfile: ApiGateways/YarpApiGateWay/Dockerfile
  
  #shopping.web:
  # image: shopping.web
    #build:
     # context: .
      #dockerfile: WebApps/Shopping.Web/Dockerfile




volumes: 
  postgres_catalog:
  postgres_basket:
  
  
